### PR TITLE
Update xkcd.lgo

### PR DESCRIPTION
**Pull request by jemmajeffree**
Have extended from 3:00:00 to 3:10:00

### CODE REVIEW

**Comment by theinternetftw** [comment]
I've pulled the 03:00:00 to 03:10:00 commit.  Will now update to 03:20:00.

**Comment by edegeltje** [comment]
there seem to be different versions of the sound file, as the piece of text at 3:18:33 doesn't appear in my version...

**Comment by theinternetftw** [comment]
Quite possibly. I've been noticing timestamps from contributors not quite matching up with what I've got on my end.

Maybe it picks interjections at random? So far the picture's coming together though.

For reference, the sha1 for the radio.mp3 I've got is fb2292dd1e021ae01b949ef2673f6be00e496e49

**Comment by edegeltje** [comment]
i just found out what it is (i think). somehow the downloaded file is different from the file when you open it in your browser.
it may be helpfull if either 1: you explicitly state that we should use the browser version or 2: you put the soundfile which we should use in the repo

**Comment by theinternetftw** [comment]
Well, I think it's unlikely that there'd be just 2 versions, unless it's a caching mistake.

If there are different versions, I expect multiple versions, or it generating random versions.

Did you manage to get a version of the file with that hash?

Regardless, I'll make a note in the README.

**Pull request merged**
