### PR TITLE
Machine transcription for the missing parts

### PR DESCRIPTION
**Pull request by jp-hoehmann**
Hi, I have run the audio file through a better transcription system and merged in the result. This is still far from perfect (some 200 stanzas are commented out, because the machine wasn't able to transcribe them correctly, but a few incorrectly transcribed ones slipped through, messing up the result). Still, for large parts of this, it is probably easier to fix the errors in the machine translation, than to transcribe it directly from the audio, so I thought I'd make a PR.

Let me know if you'd like me to add some notes with timestamps beyond the five-hour mark.

### CODE REVIEW

**Comment by jp-hoehmann** [comment]
Huh. For some reason it is marking all existing lines as deleted and recreated in the diff, even though they haven't changed at all. Lemme look into this.

**Comment by MikeWalrus** [comment]
This looks pretty good. :D
screen

**Comment by jp-hoehmann** [comment]
Ok, so the problem was Git's behaviour of automatically converting CRLF to LF upon commit. I have added .gitattributes to tell Git to keep the line endings untouched. GitHub still detects 74 deleted lines, however as far as I can tell that is just overzealous diffing. No existing code has been changed.

**Comment by ajacks-msft** [comment]
With timestamps, this would be pretty easy to start correcting.  I'm going to switch over to this branch and attempt some fixes ("one" becomes "1"). Still, where someone has done manual transcription we should probably default to that.

**Comment by Cqoicebordel** [comment]
I'm not sure it should be merged, as in this repo, the file is used only for manually verified transcription.  
But as a start, it's good.

For my transcripts, I have been using https://github.com/somebody1234/xkcd2601 machine transcription as a base, to check and correct eventual errors. And the text is mostly already cleaned.  
Maybe it should be checked and merged in that repo instead ?

**Comment by jp-hoehmann** [comment]
@ajacks-msft I have added some timestamps

**Comment by jp-hoehmann** [comment]
> where someone has done manual transcription we should probably default to that.

Yeah, definitely. This retains everything that has been manually transcribed so far.

**Comment by theinternetftw** [comment]
Left this up here as a reference, but the transcript is done now, so closing this PR.

**Pull request closed without merging**
